Adds dependabot.yml
fungover/storm pull request #17
Opened 2022-01-30 14:51 UTC by GreenGard

Add dependabot support for Maven, Github actions and Docker. Solves issue #10

2022-01-30 16:08 UTC, kappsegla requested changes
Shouldn't the directory be / for all checks?

2022-01-30 16:08 UTC, kappsegla commented on .github/dependabot.yml
> +    directory: "/.github/workflows/"
```suggestion
    directory: "/
```

2022-01-30 16:08 UTC, kappsegla commented on .github/dependabot.yml
> +    directory: "/.github/workflows/"
```suggestion
    directory: "/"
```

2022-01-30 18:15 UTC, kappsegla approved these changes
As far as I understand this will work as intended.

2022-01-31 06:52 UTC, HelenaHalldinITHS commented
Looks good!

2022-01-31 06:53 UTC, HelenaHalldinITHS approved these changes
Looks good!

2022-01-31 08:50 UTC, merged