Update java version
fungover/storm pull request #212
Opened 2024-02-05 15:42 UTC by nilssonjn

Update to java version 21, update dependencies and the dockerfile. Also added script for issue #158

closes #158
closes #197

2024-02-06 19:56 UTC, Ebyrdeu requested changes

2024-02-06 19:56 UTC, Ebyrdeu commented on pom.xml
> +                <version>3.1.0</version>
The latest verison is [3.2.5](https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-failsafe-plugin).
For some reason inteleji sugestion hasn't updated that to 3.2.5 and latest version you can see is 3.1.0 I belive.

2024-02-06 19:56 UTC, Ebyrdeu commented on pom.xml
> +        <assertj.core.version>3.25.2</assertj.core.version>
The latest version is [3.25.3](https://mvnrepository.com/artifact/org.assertj/assertj-core)

2024-02-06 19:56 UTC, Ebyrdeu commented on pom.xml
> +                <version>0.8.10</version>
The latest version is [0.8.11](https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin)

2024-02-07 07:07 UTC, Ebyrdeu approved these changes

2024-02-07 08:10 UTC, hannastigland approved these changes
Looks correct to me, thank you for contributing!

2024-02-07 11:38 UTC, merged