#95  - I'm a teapot
fungover/storm pull request #221
Opened 2024-02-10 12:57 UTC by Danback

Add /coffee endpoint with 418 I'm a Teapot response

- Implement Teapot class for handling /coffee requests.
- Update HttpParser for path extraction.
- Modify ClientHandler for /coffee response.
- Add TeapotTest for endpoint testing.

2024-02-11 20:08 UTC, Kouroshkt approved these changes

2024-02-11 20:08 UTC, Kouroshkt commented on src/test/java/org/fungover/storm/filehandler/re/TeapotTest.java
> +
Using messages for testing is good and you can guickly find the problem. Great

2024-02-12 11:53 UTC, kappsegla requested changes

2024-02-12 11:53 UTC, kappsegla commented on webroot/coffee.html
Since you are creating a response with java code when detecting the path /coffee, we don't need a file in webroot to serve. Also the path /coffee and path /coffee.html are two different paths with different responses.

2024-02-12 14:00 UTC, Danback commented on webroot/coffee.html
You're right, fixing it now.

2024-02-12 14:24 UTC, Danback commented on src/test/java/org/fungover/storm/filehandler/re/TeapotTest.java
> +        assertFalse(Teapot.isCoffeeRequest("/tea"));
Will do, thanks for the feedback!

2024-02-12 15:37 UTC, kappsegla submitted a review, later dismissed
Now it looks good.

2024-02-14 09:01 UTC, merged