Refer to Issue #64: Add the class for header uthorization
fungover/storm pull request #67
Opened 2022-02-04 02:00 UTC by robinkorkmaz1

2022-02-04 09:18 UTC, kappsegla commented on pom.xml
> -        <maven.compiler.target>${maven.compiler.source}</maven.compiler.target>
We do not want to update pom.xml java version.

2022-02-04 09:20 UTC, kappsegla requested changes
Remove changes to pom.xml from pullrequest that changes java version from 17 to 16

2022-02-08 18:31 UTC, robinkorkmaz1 reviewed
Ok

2022-02-09 13:26 UTC, kappsegla commented
> Ok
Should be possible to fix this with:
git checkout pull-request-branch

Overwrite the modified file(s) with the file in another branch:
git checkout origin/master -- pom.xml

Commit and push it to the remote:
git commit -m "removed a modified file from PR"
git push

2022-02-10 17:27 UTC, BorvD approved these changes

2024-02-07 19:30 UTC, kappsegla commented
Stale implementation. Lets close it and open a new PR if the issue still seams relevant.

2024-02-07 19:30 UTC, closed without merging